name: Allium CI/CD Pipeline

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Lint Python code
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Validate Jinja2 templates
      run: |
        # Check template syntax
        find allium/templates/ -name "*.html" -exec python -c "
        from jinja2 import Environment, FileSystemLoader, TemplateSyntaxError
        import sys
        import os
        try:
            template_path = '{}'
            # Extract relative path from allium/templates/
            relative_path = os.path.relpath(template_path, 'allium/templates')
            
            env = Environment(loader=FileSystemLoader('allium/templates'))
            env.get_template(relative_path)
            print('✅ Template {} is valid'.format(relative_path))
        except TemplateSyntaxError as e:
            print('❌ Template {} has syntax error: {}'.format(relative_path, e))
            sys.exit(1)
        except Exception as e:
            print('⚠️  Could not validate {}: {}'.format(relative_path, e))
        " \;
        
    - name: Run Python tests
      run: |
        python -m pytest tests/ -v --cov=. --cov-report=xml
        
    - name: Security scan
      run: |
        # Check for common security issues
        bandit -r . -f json -o bandit-report.json || true
        # Check for known vulnerabilities in dependencies
        safety check --json --output safety-report.json || true
        
    - name: Test AROI leaderboard generation
      run: |
        # Test the leaderboard generation process
        cd allium
        python -c "
        import sys
        sys.path.insert(0, 'lib')
        try:
            import aroileaders
            print('✅ AROI leaders module imports successfully')
        except ImportError as e:
            print('❌ Cannot import aroileaders:', e)
            # This is not a critical failure for CI, just informational
            print('ℹ️  Module import failed, but this is expected in CI environment')
        "
        
    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.11'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        
  template-quality:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install template tools
      run: |
        pip install jinja2 djlint
        
    - name: Check template quality
      run: |
        # Check for template best practices
        echo "🔍 Checking for template security issues..."
        
        # Check for unsafe filters
        if grep -r "| safe" allium/templates/ 2>/dev/null; then
          echo "⚠️  Found '| safe' filters - review for XSS risks"
        else
          echo "✅ No unsafe filters found"
        fi
        
        # Check autoescape configuration
        if grep -r "autoescape.*false" allium/templates/ 2>/dev/null; then
          echo "❌ Found disabled autoescape - security risk!"
          exit 1
        else
          echo "✅ Autoescape properly configured"
        fi
        
        # Lint HTML/Jinja2 templates
        djlint allium/templates/ --check --quiet || echo "⚠️  Template formatting issues found"
        
  performance:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install memory-profiler
        
    - name: Performance test
      run: |
        # Test template rendering performance
        cd allium
        python -c "
        import time
        import tracemalloc
        import sys
        
        sys.path.insert(0, 'lib')
        
        tracemalloc.start()
        start_time = time.time()
        
        try:
            # Test basic Python imports and operations
            print('⏱️  Starting performance test...')
            
            # Import Jinja2 and test template loading
            from jinja2 import Environment, FileSystemLoader
            env = Environment(loader=FileSystemLoader('templates'))
            
            # Test template loading performance
            template_files = ['index.html', 'skeleton.html']
            for template_file in template_files:
                try:
                    template = env.get_template(template_file)
                    print(f'✅ Successfully loaded template: {template_file}')
                except Exception as e:
                    print(f'⚠️  Could not load template {template_file}: {e}')
            
            end_time = time.time()
            current, peak = tracemalloc.get_traced_memory()
            tracemalloc.stop()
            
            print(f'⏰ Execution time: {end_time - start_time:.2f} seconds')
            print(f'💾 Memory usage: {current / 1024 / 1024:.1f} MB')
            print(f'💾 Peak memory: {peak / 1024 / 1024:.1f} MB')
            
            # Alert if performance degrades significantly  
            if end_time - start_time > 10:
                print('⚠️  Template loading took longer than expected')
            if peak / 1024 / 1024 > 100:
                print('⚠️  Memory usage higher than expected')
            
            print('✅ Performance test completed successfully')
                
        except Exception as e:
            print(f'❌ Performance test failed: {e}')
            print('ℹ️  This is not a critical failure for CI')
        " 